### ISSUE TITLE
Support for HiDPI screens

### ISSUE THREAD

**Issue by valb3r** [tzaeschke/ode4j#126]
For HiDPI screens all demos are rendered in the lower left quarter of the screen:
<img width="681" alt="Screenshot 2023-09-05 at 09 55 10" src="https://github.com/tzaeschke/ode4j/assets/18463491/f6d8302e-55a5-4a9a-98a1-dc15afd5e798">

The PR: https://github.com/tzaeschke/ode4j/pull/125 fixes this issue for Java part

**Comment by tzaeschke** [comment]
Thanks for the PR!
This has been released with v0.5.1.
