### ISSUE TITLE
how do i setPosition on a slider?

### ISSUE THREAD

**Issue by i-make-robots** [tzaeschke/ode4j#143]
I'm building a simulation of a leg on a vertical slider like this:

![373922140-0d950660-cf0b-4bab-b233-d5743857411d](https://github.com/user-attachments/assets/34ce2546-70ba-4a84-81b0-9b0df1427d21)

I have a hip box with a hinge to a thigh to a hinge to a calf. the hip box is attached to the slider. the slider's position is the floor. I expected to start with a slider.getPosition of ~28. instead it is set to zero.  Is there some way to set the position to my expected value, or change this behavior?  I also tried to move the hip to the slider center, set the axis, then move the hip back to get some distance.  No dice.  So.... what's the "right" way to do this, please?

**Comment by tzaeschke** [comment]
Please use the forums for questions.
