### ISSUE TITLE
DxQuickStep: incorrect avel computation: tacc is scaled multiple times

### ISSUE THREAD

**Issue by neduard** [tzaeschke/ode4j#38]
Found this after comparing ode4j behaviour with VRep (using the C implementation of ODE):
I was applying an off-cenetered force to a body, but it caused a VERY slow increase in angular momentum compared to VRep.
So I checked the ode4j source code and found this line:
https://github.com/tzaeschke/ode4j/blob/master/core/src/main/java/org/ode4j/ode/internal/DxQuickStep.java#L1886

Which scales the **whole** `tacc` vector three times. Compare to the C++ version (`quickstep.cpp`):
```c++
for (dxBody *const *bodycurr = body; bodycurr != bodyend; invIrow += 12, bodycurr++) {
    dxBody *b = *bodycurr;
    dReal body_invMass_mul_stepsize = stepsize * b->invMass;
    for (unsigned int j=0; j<3; j++) {
        b->lvel[j] += body_invMass_mul_stepsize * b->facc[j];
        b->tacc[j] *= stepsize;
    }
    dMultiplyAdd0_331 (b->avel, invIrow, b->tacc);
}
```

**Comment by tzaeschke** [comment]
Thanks, very nice catch!
I merged it and removed the loop altogether.
