### ISSUE TITLE
Incorrect assert

### ISSUE THREAD

**Issue by ppiastucki** [tzaeschke/ode4j#46]
Hi,

It looks like the following assertion is not correct:
	public void dGeomSetBody (DxBody b)
	{
		//dAASSERT (g);
		dUASSERT (b == null || (_gflags & GEOM_PLACEABLE) == 0,
		"geom must be placeable");

Instead it should be:
		dUASSERT (b == null || (_gflags & GEOM_PLACEABLE) != 0,

Respective line of code in ODE:

    dUASSERT (b == NULL || (g->gflags & GEOM_PLACEABLE),"geom must be placeable");

**Comment by tzaeschke** [comment]
Thanks, fixed in fe9ae4c4de628c24b51865d1225759cd1f17b9dd
