### ISSUE TITLE
missing helper methods?

### ISSUE THREAD

**Issue by chriscamacho** [tzaeschke/ode4j#52]
While I can do...

		body.asInstanceOf[org.ode4j.ode.internal.DxBody].dBodyDestroy()
		geom.asInstanceOf[org.ode4j.ode.internal.DxGeom].dGeomDestroy()

wouldn't these be better in the helper object - or even in the body and geom front end classes

**Comment by jfelrod1960** [comment]
Why not do the following?

DBody.destroy() and DGeom.destroy()

**Comment by chriscamacho** [comment]
DOH! I think I must have been looking for bodyDestroy and geomDestroy methods....

**Comment by tzaeschke** [comment]
Thanks, good that this could be resolved :-)
