### ISSUE TITLE
Looks like instrumentation/debug code has not been removed

### ISSUE THREAD

**Issue by jfelrod1960** [tzaeschke/ode4j#55]
When running the demos, instrumentation or debug code is outputting.  Don't know if that were the author's intentions.  It is showing what look like to be time duration output.

Jeff

**Comment by ppiastucki** [comment]
My bad, I let some debugging code slip through even though there was a FIXME comment left there :)

**Comment by jfelrod1960** [comment]
No problem Piotr.  I figured as much.  Thanks man!

**Comment by tzaeschke** [comment]
Okay, I just merged it and pushed a mvn snapshot. Thanks for reporting!
