### ISSUE TITLE
Wiki should include complete HOWTO for importing the whole project via Maven

### ISSUE THREAD

**Issue by tzaeschke** [tzaeschke/ode4j#6]
Currently the according wiki page only describes how to use maven for the 'core' artifact.

The problem with importing the whole project is to get the import of native libraries to work, which are used by lwjgl.
For eclipse there is a special Maven-native plug-in, but seems to collide with the hierarchical project structure of ode4j.

**Comment by Levvy055** [comment]
As it's given there: [Maven od4j](https://mvnrepository.com/artifact/org.ode4j/parent/0.3.0)
and for core: [Maven ode4j Core](https://mvnrepository.com/artifact/org.ode4j/core/0.3.0)

**Comment by tzaeschke** [comment]
The problem is that the plain .pom import works only for the core and the cpp part. The demos need lwjgl (which is available via Maven), but lwjgl needs native libraries (last time I checked. These are platform dependent, which is harder to get right in Maven. But I haven't tried this in a while, 2013 apparently, so maybe import via maven is more straight forward nowadays? Also, importing project hierarchies in Eclipse still seems to be a bit weird.

**Comment by tzaeschke** [comment]
It appears the this may now work better with LWJGL, so maybe I should just point to their [Wiki](https://github.com/LWJGL/lwjgl3-wiki/wiki/1.2.-Install). That leaves importing project hierarchies.

**Comment by tzaeschke** [comment]
This is completely solved with LWJGL 3.0. It works without any additional config/settings.
