### ISSUE TITLE
Trying to see how DRay can be used to create a Raycast Vehicle

### ISSUE THREAD

**Issue by jfelrod1960** [tzaeschke/ode4j#75]
I tried a simple test to see if collision is detected between an instance of DRay and DPlane, but to no avail.  So I perused the code and cannot find where DRay functions are called for collision detect.  I would appreciate any help.

Jeff

**Comment by tzaeschke** [comment]
`DemoCollision` has a test method `test_ray_and_plane()`. I haven't checked were the collision is handled inside ODE, but the test method reports that it works. Does that help?

**Comment by tzaeschke** [comment]
The collision is handled in `dCollideRayPlane(...)` in `DxRay`.

**Comment by jfelrod1960** [comment]
I just completely missed DemoCollision.  I'm sorry.  Thank you! :)

**Comment by tzaeschke** [comment]
No problem :-)
