### ISSUE TITLE
Observer falls throught triangle terrain

### ISSUE THREAD

**Issue by ghost** [tzaeschke/ode4j#9]
Hi, in my WalkOnTheMoon Applet, the observer is a sphere object.
Unfortunately, if I do not set damping on the observer, it can happen,
that he falls through the terrain. I can help fix this, but I need to know,
which files are to be touched.
Sincerely
Thorsten

**Comment by tzaeschke** [comment]
Probably not relevant anymore. Please open new issue if it is observed again.
